[package]
name = "swarm-intelligence"
version = "2.0.0"
edition = "2021"
description = "Swarm intelligence for Ninja Gekko"

[dependencies]
serde = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }